name:                NoviSteps4Q
version:             0.0.0
github:              nobsun/NoviSteps4Q
license:             BSD3
author:              Nobuo Yamashita
maintainer:          nobsun@sampou.org
copyright:           © 2024, Nobuo Yamashita

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/NoviSteps4Q#readme>

dependencies:
- base >= 4.7 && < 5
- utf8-string
- unicode-show
- hspec
- main-tester
- Cabal
- Cabal-syntax
- QuickCheck
- adjunctions
- array
- attoparsec
- bifunctors
- binary
- bitvec
- bytestring
- comonad
- containers
- contravariant
- deepseq
- directory
- distributive
- exceptions
- extra
- fgl
- filepath
- free
- ghc-bignum
- ghc-boot-th
- ghc-prim
- hashable
- heaps
- indexed-traversable
- indexed-traversable-instances
- integer-gmp
- integer-logarithms
- kan-extensions
- lens
- linear-base
- list-t
- massiv
- megaparsec
- mono-traversable
- mtl
- mutable-containers
- mwc-random
- parallel
- parsec
- parser-combinators
- pretty
- primitive
- process
- profunctors
- psqueues
- random
- reflection
- regex-tdfa
- safe-exceptions
- scientific
- semialign
- semigroupoids
- split
- stm
- strict
- strict-lens
- tagged
- template-haskell
- text
- tf-random
- these
- these-lens
- time
- transformers
- trifecta
- unboxing-vector
- unix
- unordered-containers
- utility-ht
- vector
- vector-algorithms
- vector-stream
- vector-th-unbox
- xhtml

language: GHC2021

default-extensions:
- ImplicitParams
- ImportQualifiedPost
- LambdaCase
- LexicalNegation
- MultiWayIf
- NPlusKPatterns
- OverloadedStrings
- DataKinds
- PolyKinds
- NoStarIsType
- TypeFamilyDependencies
- UndecidableInstances

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-orphans

library:
  source-dirs: src

executables:
  abc394c:
    main:               Main.hs
    source-dirs:        app/abc394c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc019c:
    main:               Main.hs
    source-dirs:        app/abc019c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc016c:
    main:               Main.hs
    source-dirs:        app/abc016c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  csr002k:
    main:               Main.hs
    source-dirs:        app/csr002k
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  csr002f:
    main:               Main.hs
    source-dirs:        app/csr002f
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc021b:
    main:               Main.hs
    source-dirs:        app/abc021b
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc244c:
    main:               Main.hs
    source-dirs:        app/abc244c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc296c:
    main:               Main.hs
    source-dirs:        app/abc296c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc303c:
    main:               Main.hs
    source-dirs:        app/abc303c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc310c:
    main:               Main.hs
    source-dirs:        app/abc310c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc392c:
    main:               Main.hs
    source-dirs:        app/abc392c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  abc393c:
    main:               Main.hs
    source-dirs:        app/abc393c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  mindifference:
    main:               Main.hs
    source-dirs:        app/mindifference
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  specialtrains:
    main:               Main.hs
    source-dirs:        app/specialtrains
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  painttomakearectangle:
    main:               Main.hs
    source-dirs:        app/painttomakearectangle
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  dubiousdocument2:
    main:               Main.hs
    source-dirs:        app/dubiousdocument2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  derangement:
    main:               Main.hs
    source-dirs:        app/derangement
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  makearectangle:
    main:               Main.hs
    source-dirs:        app/makearectangle
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  variouskagamimochi:
    main:               Main.hs
    source-dirs:        app/variouskagamimochi
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  operate1:
    main:               Main.hs
    source-dirs:        app/operate1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  multipleclocks:
    main:               Main.hs
    source-dirs:        app/multipleclocks
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  4adjacent:
    main:               Main.hs
    source-dirs:        app/4adjacent
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  pushpush:
    main:               Main.hs
    source-dirs:        app/pushpush
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  bugged:
    main:               Main.hs
    source-dirs:        app/bugged
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  monotonicallyincreasing:
    main:               Main.hs
    source-dirs:        app/monotonicallyincreasing
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  caracalvsmonster:
    main:               Main.hs
    source-dirs:        app/caracalvsmonster
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  removeonecharacter:
    main:               Main.hs
    source-dirs:        app/removeonecharacter
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  humidifier2:
    main:               Main.hs
    source-dirs:        app/humidifier2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  dango:
    main:               Main.hs
    source-dirs:        app/dango
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  bruteforceattack:
    main:               Main.hs
    source-dirs:        app/bruteforceattack
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  doublecamelcasesort:
    main:               Main.hs
    source-dirs:        app/doublecamelcasesort
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  jjooii:
    main:               Main.hs
    source-dirs:        app/jjooii
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  11_22substring:
    main:               Main.hs
    source-dirs:        app/11_22substring
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  replacing:
    main:               Main.hs
    source-dirs:        app/replacing
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  writeanderase:
    main:               Main.hs
    source-dirs:        app/writeanderase
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  enumerationofsubsets1:
    main:               Main.hs
    source-dirs:        app/enumerationofsubsets1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  lrudinstructions2:
    main:               Main.hs
    source-dirs:        app/lrudinstructions2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  ff:
    main:               Main.hs
    source-dirs:        app/ff
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  poemonlinejudge:
    main:               Main.hs
    source-dirs:        app/poemonlinejudge
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  thekthtimequery:
    main:               Main.hs
    source-dirs:        app/thekthtimequery
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  greenbin:
    main:               Main.hs
    source-dirs:        app/greenbin
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  past202010openf:
    main:               Main.hs
    source-dirs:        app/past202010openf
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  queue0:
    main:               Main.hs
    source-dirs:        app/queue0
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  together:
    main:               Main.hs
    source-dirs:        app/together
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  problemset:
    main:               Main.hs
    source-dirs:        app/problemset
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  fivetransportations:
    main:               Main.hs
    source-dirs:        app/fivetransportations
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  avoidknightattack:
    main:               Main.hs
    source-dirs:        app/avoidknightattack
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  streamline:
    main:               Main.hs
    source-dirs:        app/streamline
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  colorfulsmiles2:
    main:               Main.hs
    source-dirs:        app/colorfulsmiles2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  bbqeasy:
    main:               Main.hs
    source-dirs:        app/bbqeasy
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  maximalvalue:
    main:               Main.hs
    source-dirs:        app/maximalvalue
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  stonegames1:
    main:               Main.hs
    source-dirs:        app/stonegames1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  poweroftwo:
    main:               Main.hs
    source-dirs:        app/poweroftwo
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  moveonsquares1:
    main:               Main.hs
    source-dirs:        app/moveonsquares1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  travel1:
    main:               Main.hs
    source-dirs:        app/travel1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  climbstairs:
    main:               Main.hs
    source-dirs:        app/climbstairs
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  ballsimulation:
    main:               Main.hs
    source-dirs:        app/ballsimulation
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  switchingligthts:
    main:               Main.hs
    source-dirs:        app/switchingligthts
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  priorityqueue:
    main:               Main.hs
    source-dirs:        app/priorityqueue
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  queue:
    main:               Main.hs
    source-dirs:        app/queue
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  stack:
    main:               Main.hs
    source-dirs:        app/stack
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  changeandreverse:
    main:               Main.hs
    source-dirs:        app/changeandreverse
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  triangle:
    main:               Main.hs
    source-dirs:        app/triangle
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  blackcompany1:
    main:               Main.hs
    source-dirs:        app/blackcompany1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  travel2:
    main:               Main.hs
    source-dirs:        app/travel2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  binarysearch1:
    main:               Main.hs
    source-dirs:        app/binarysearch1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  maxsum:
    main:               Main.hs
    source-dirs:        app/maxsum
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  handsonring:
    main:               Main.hs
    source-dirs:        app/handsonring
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  candybutton:
    main:               Main.hs
    source-dirs:        app/candybutton
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  findseiza:
    main:               Main.hs
    source-dirs:        app/findseiza
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  5qsentou:
    main:               Main.hs
    source-dirs:        app/5qsentou
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  party:
    main:               Main.hs
    source-dirs:        app/party
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  circlecrosstamps:
    main:               Main.hs
    source-dirs:        app/circlecrosstamps
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  poster:
    main:               Main.hs
    source-dirs:        app/poster
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  library2:
    main:               Main.hs
    source-dirs:        app/library2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  dance:
    main:               Main.hs
    source-dirs:        app/dance
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  irohalovesstringabc:
    main:               Main.hs
    source-dirs:        app/irohalovesstringabc
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  atcodeerandelectionreport:
    main:               Main.hs
    source-dirs:        app/atcodeerandelectionreport
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  1dreversi:
    main:               Main.hs
    source-dirs:        app/1dreversi
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  gohome:
    main:               Main.hs
    source-dirs:        app/gohome
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  chooseintegers:
    main:               Main.hs
    source-dirs:        app/chooseintegers
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  travelingtakahashiproblem:
    main:               Main.hs
    source-dirs:        app/travelingtakahashiproblem
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  seats:
    main:               Main.hs
    source-dirs:        app/seats
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  christmaseve:
    main:               Main.hs
    source-dirs:        app/christmaseve
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  unification:
    main:               Main.hs
    source-dirs:        app/unification
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  secretnumber:
    main:               Main.hs
    source-dirs:        app/secretnumber
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  cheese:
    main:               Main.hs
    source-dirs:        app/cheese
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  product:
    main:               Main.hs
    source-dirs:        app/product
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  brutmphyhiizp:
    main:               Main.hs
    source-dirs:        app/brutmphyhiizp
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  maxmex:
    main:               Main.hs
    source-dirs:        app/maxmex
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  standings:
    main:               Main.hs
    source-dirs:        app/standings
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  moveit:
    main:               Main.hs
    source-dirs:        app/moveit
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  makethemnarrow:
    main:               Main.hs
    source-dirs:        app/makethemnarrow
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  intersectionofcuboids:
    main:               Main.hs
    source-dirs:        app/intersectionofcuboids
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  minimumglutton:
    main:               Main.hs
    source-dirs:        app/minimumglutton
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  ballsandbagquery:
    main:               Main.hs
    source-dirs:        app/ballsandbagquery
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  enumeratesequences:
    main:               Main.hs
    source-dirs:        app/enumeratesequences
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  tripleatack:
    main:               Main.hs
    source-dirs:        app/tripleatack
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  worldladder:
    main:               Main.hs
    source-dirs:        app/worldladder
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  add-entry:
    main:                Main.hs
    source-dirs:         app/add-entry
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  judge-hs:
    main:                Main.hs
    source-dirs:         app/judge-hs
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

  NoviSteps4Q:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps4Q

tests:
  NoviSteps4Q-test:
    main:                spec.hs
    source-dirs:         test
    dependencies:
    - NoviSteps4Q
    - hspec
    - main-tester

  NoviSteps4Q-doctest:
    main:                doctests.hs
    source-dirs:         test
    dependencies:
    - NoviSteps4Q
    - doctest
